USE gestion_reunions;

DROP TABLE PARTICIPATIONS CASCADE;
DROP TABLE PARTICIPATIONSTATUS CASCADE;
DROP TABLE INVITATION CASCADE;
DROP TABLE MESSAGES CASCADE;
DROP TABLE UTILISATEURS CASCADE;
DROP TABLE POINTDORDRES CASCADE;
DROP TABLE REUNIONS CASCADE;
DROP TABLE DOSSIERS CASCADE;